name: Application Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_SERVER_IP: ${{ needs.terraform.outputs.app_server_ip }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$APP_SERVER_IP << 'EOF'
          cd /home/ubuntu/Basic-nodejs-app
          git pull origin master
          docker-compose down
          docker-compose up -d --build
          EOF
